"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Header(object):

    __slots__ = ["seq", "stamp", "frame_id"]

    __typenames__ = ["int32_t", "int64_t", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.seq = 0
        """ LCM Type: int32_t """
        self.stamp = 0
        """ LCM Type: int64_t """
        self.frame_id = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(Header._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iq", self.seq, self.stamp))
        __frame_id_encoded = self.frame_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__frame_id_encoded)+1))
        buf.write(__frame_id_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Header._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Header._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Header()
        self.seq, self.stamp = struct.unpack(">iq", buf.read(12))
        __frame_id_len = struct.unpack('>I', buf.read(4))[0]
        self.frame_id = buf.read(__frame_id_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Header in parents: return 0
        tmphash = (0xc91376e81efc25d8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Header._packed_fingerprint is None:
            Header._packed_fingerprint = struct.pack(">Q", Header._get_hash_recursive([]))
        return Header._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Header._get_packed_fingerprint())[0]

