/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __foxglove_msgs_LinePrimitive_hpp__
#define __foxglove_msgs_LinePrimitive_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "geometry_msgs/Pose.hpp"
#include "geometry_msgs/Point.hpp"
#include "foxglove_msgs/Color.hpp"
#include "foxglove_msgs/Color.hpp"

namespace foxglove_msgs
{

class LinePrimitive
{
    public:
        int32_t    points_length;

        int32_t    colors_length;

        int32_t    indices_length;

        uint8_t    type;

        geometry_msgs::Pose pose;

        double     thickness;

        int8_t     scale_invariant;

        /**
         * LCM Type: geometry_msgs.Point[points_length]
         */
        std::vector< geometry_msgs::Point > points;

        foxglove_msgs::Color color;

        /**
         * LCM Type: foxglove_msgs.Color[colors_length]
         */
        std::vector< foxglove_msgs::Color > colors;

        /**
         * LCM Type: int32_t[indices_length]
         */
        std::vector< int32_t > indices;

    public:
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   LINE_STRIP = 0;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   LINE_LOOP = 1;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   LINE_LIST = 2;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "LinePrimitive"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int LinePrimitive::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LinePrimitive::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LinePrimitive::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t LinePrimitive::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* LinePrimitive::getTypeName()
{
    return "LinePrimitive";
}

int LinePrimitive::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->points_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->colors_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->indices_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->pose._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->thickness, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->scale_invariant, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->points_length; a0++) {
        tlen = this->points[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->color._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->colors_length; a0++) {
        tlen = this->colors[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->indices_length > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->indices[0], this->indices_length);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LinePrimitive::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->points_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->colors_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->indices_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->pose._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->thickness, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->scale_invariant, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->points.resize(this->points_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->points_length; a0++) {
        tlen = this->points[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->color._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->colors.resize(this->colors_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->colors_length; a0++) {
        tlen = this->colors[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->indices_length) {
        this->indices.resize(this->indices_length);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->indices[0], this->indices_length);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LinePrimitive::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, 1);
    enc_size += this->pose._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->points_length; a0++) {
        enc_size += this->points[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->color._getEncodedSizeNoHash();
    for (int a0 = 0; a0 < this->colors_length; a0++) {
        enc_size += this->colors[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, this->indices_length);
    return enc_size;
}

uint64_t LinePrimitive::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == LinePrimitive::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, LinePrimitive::getHash };

    uint64_t hash = 0x3b39f8eb653b3cd3LL +
         geometry_msgs::Pose::_computeHash(&cp) +
         geometry_msgs::Point::_computeHash(&cp) +
         foxglove_msgs::Color::_computeHash(&cp) +
         foxglove_msgs::Color::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
