"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import geometry_msgs

import std_msgs

class AccelWithCovarianceStamped(object):

    __slots__ = ["header", "accel"]

    __typenames__ = ["std_msgs.Header", "geometry_msgs.AccelWithCovariance"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.accel = geometry_msgs.AccelWithCovariance()
        """ LCM Type: geometry_msgs.AccelWithCovariance """

    def encode(self):
        buf = BytesIO()
        buf.write(AccelWithCovarianceStamped._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.accel._get_packed_fingerprint() == geometry_msgs.AccelWithCovariance._get_packed_fingerprint()
        self.accel._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AccelWithCovarianceStamped._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AccelWithCovarianceStamped._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = AccelWithCovarianceStamped()
        self.header = std_msgs.Header._decode_one(buf)
        self.accel = geometry_msgs.AccelWithCovariance._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if AccelWithCovarianceStamped in parents: return 0
        newparents = parents + [AccelWithCovarianceStamped]
        tmphash = (0xf012322e268930c2+ std_msgs.Header._get_hash_recursive(newparents)+ geometry_msgs.AccelWithCovariance._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if AccelWithCovarianceStamped._packed_fingerprint is None:
            AccelWithCovarianceStamped._packed_fingerprint = struct.pack(">Q", AccelWithCovarianceStamped._get_hash_recursive([]))
        return AccelWithCovarianceStamped._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AccelWithCovarianceStamped._get_packed_fingerprint())[0]

