"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import geometry_msgs

import std_msgs

class WrenchStamped(object):

    __slots__ = ["header", "wrench"]

    __typenames__ = ["std_msgs.Header", "geometry_msgs.Wrench"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.wrench = geometry_msgs.Wrench()
        """ LCM Type: geometry_msgs.Wrench """

    def encode(self):
        buf = BytesIO()
        buf.write(WrenchStamped._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.wrench._get_packed_fingerprint() == geometry_msgs.Wrench._get_packed_fingerprint()
        self.wrench._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != WrenchStamped._get_packed_fingerprint():
            raise ValueError("Decode error")
        return WrenchStamped._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = WrenchStamped()
        self.header = std_msgs.Header._decode_one(buf)
        self.wrench = geometry_msgs.Wrench._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if WrenchStamped in parents: return 0
        newparents = parents + [WrenchStamped]
        tmphash = (0xecb7c2d77fc5d5e0+ std_msgs.Header._get_hash_recursive(newparents)+ geometry_msgs.Wrench._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if WrenchStamped._packed_fingerprint is None:
            WrenchStamped._packed_fingerprint = struct.pack(">Q", WrenchStamped._get_hash_recursive([]))
        return WrenchStamped._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", WrenchStamped._get_packed_fingerprint())[0]

