/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __sensor_msgs_MultiDOFJointState_hpp__
#define __sensor_msgs_MultiDOFJointState_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include <string>
#include "std_msgs/Header.hpp"
#include "geometry_msgs/Transform.hpp"
#include "geometry_msgs/Twist.hpp"
#include "geometry_msgs/Wrench.hpp"

namespace sensor_msgs
{

class MultiDOFJointState
{
    public:
        int32_t    joint_names_length;

        int32_t    transforms_length;

        int32_t    twist_length;

        int32_t    wrench_length;

        std_msgs::Header header;

        /**
         * LCM Type: string[joint_names_length]
         */
        std::vector< std::string > joint_names;

        /**
         * LCM Type: geometry_msgs.Transform[transforms_length]
         */
        std::vector< geometry_msgs::Transform > transforms;

        /**
         * LCM Type: geometry_msgs.Twist[twist_length]
         */
        std::vector< geometry_msgs::Twist > twist;

        /**
         * LCM Type: geometry_msgs.Wrench[wrench_length]
         */
        std::vector< geometry_msgs::Wrench > wrench;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "MultiDOFJointState"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int MultiDOFJointState::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int MultiDOFJointState::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int MultiDOFJointState::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t MultiDOFJointState::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* MultiDOFJointState::getTypeName()
{
    return "MultiDOFJointState";
}

int MultiDOFJointState::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->joint_names_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->transforms_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->twist_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->wrench_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->joint_names_length; a0++) {
        char* __cstr = const_cast<char*>(this->joint_names[a0].c_str());
        tlen = __string_encode_array(
            buf, offset + pos, maxlen - pos, &__cstr, 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->transforms_length; a0++) {
        tlen = this->transforms[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->twist_length; a0++) {
        tlen = this->twist[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->wrench_length; a0++) {
        tlen = this->wrench[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int MultiDOFJointState::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->joint_names_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->transforms_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->twist_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->wrench_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->joint_names.resize(this->joint_names_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->joint_names_length; a0++) {
        int32_t __elem_len;
        tlen = __int32_t_decode_array(
            buf, offset + pos, maxlen - pos, &__elem_len, 1);
        if(tlen < 0) return tlen; else pos += tlen;
        if(__elem_len > maxlen - pos) return -1;
        this->joint_names[a0].assign(static_cast<const char*>(buf) + offset + pos, __elem_len -  1);
        pos += __elem_len;
    }

    try {
        this->transforms.resize(this->transforms_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->transforms_length; a0++) {
        tlen = this->transforms[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->twist.resize(this->twist_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->twist_length; a0++) {
        tlen = this->twist[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->wrench.resize(this->wrench_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->wrench_length; a0++) {
        tlen = this->wrench[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int MultiDOFJointState::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->header._getEncodedSizeNoHash();
    for (int a0 = 0; a0 < this->joint_names_length; a0++) {
        enc_size += this->joint_names[a0].size() + 4 + 1;
    }
    for (int a0 = 0; a0 < this->transforms_length; a0++) {
        enc_size += this->transforms[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->twist_length; a0++) {
        enc_size += this->twist[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->wrench_length; a0++) {
        enc_size += this->wrench[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t MultiDOFJointState::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == MultiDOFJointState::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, MultiDOFJointState::getHash };

    uint64_t hash = 0x15ca331f6f9f4fbcLL +
         std_msgs::Header::_computeHash(&cp) +
         geometry_msgs::Transform::_computeHash(&cp) +
         geometry_msgs::Twist::_computeHash(&cp) +
         geometry_msgs::Wrench::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
