/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __sensor_msgs_TimeReference_hpp__
#define __sensor_msgs_TimeReference_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>
#include "std_msgs/Header.hpp"
#include "std_msgs/Time.hpp"

namespace sensor_msgs
{

class TimeReference
{
    public:
        std_msgs::Header header;

        std_msgs::Time time_ref;

        std::string source;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "TimeReference"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int TimeReference::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int TimeReference::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int TimeReference::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t TimeReference::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* TimeReference::getTypeName()
{
    return "TimeReference";
}

int TimeReference::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->time_ref._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    char* source_cstr = const_cast<char*>(this->source.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &source_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int TimeReference::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->time_ref._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __source_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__source_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__source_len__ > maxlen - pos) return -1;
    this->source.assign(
        static_cast<const char*>(buf) + offset + pos, __source_len__ - 1);
    pos += __source_len__;

    return pos;
}

int TimeReference::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += this->time_ref._getEncodedSizeNoHash();
    enc_size += this->source.size() + 4 + 1;
    return enc_size;
}

uint64_t TimeReference::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == TimeReference::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, TimeReference::getHash };

    uint64_t hash = 0x1a6b1c8c5abae6dbLL +
         std_msgs::Header::_computeHash(&cp) +
         std_msgs::Time::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
