/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __visualization_msgs_InteractiveMarkerFeedback_hpp__
#define __visualization_msgs_InteractiveMarkerFeedback_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>
#include "std_msgs/Header.hpp"
#include "geometry_msgs/Pose.hpp"
#include "geometry_msgs/Point.hpp"

namespace visualization_msgs
{

class InteractiveMarkerFeedback
{
    public:
        std_msgs::Header header;

        std::string client_id;

        std::string marker_name;

        std::string control_name;

        uint8_t    event_type;

        geometry_msgs::Pose pose;

        int32_t    menu_entry_id;

        geometry_msgs::Point mouse_point;

        int8_t     mouse_point_valid;

    public:
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   KEEP_ALIVE = 0;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   POSE_UPDATE = 1;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   MENU_SELECT = 2;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   BUTTON_CLICK = 3;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   MOUSE_DOWN = 4;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   MOUSE_UP = 5;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "InteractiveMarkerFeedback"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int InteractiveMarkerFeedback::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int InteractiveMarkerFeedback::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int InteractiveMarkerFeedback::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t InteractiveMarkerFeedback::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* InteractiveMarkerFeedback::getTypeName()
{
    return "InteractiveMarkerFeedback";
}

int InteractiveMarkerFeedback::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    char* client_id_cstr = const_cast<char*>(this->client_id.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &client_id_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* marker_name_cstr = const_cast<char*>(this->marker_name.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &marker_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* control_name_cstr = const_cast<char*>(this->control_name.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &control_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->event_type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->pose._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->menu_entry_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mouse_point._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->mouse_point_valid, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int InteractiveMarkerFeedback::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __client_id_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__client_id_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__client_id_len__ > maxlen - pos) return -1;
    this->client_id.assign(
        static_cast<const char*>(buf) + offset + pos, __client_id_len__ - 1);
    pos += __client_id_len__;

    int32_t __marker_name_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__marker_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__marker_name_len__ > maxlen - pos) return -1;
    this->marker_name.assign(
        static_cast<const char*>(buf) + offset + pos, __marker_name_len__ - 1);
    pos += __marker_name_len__;

    int32_t __control_name_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__control_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__control_name_len__ > maxlen - pos) return -1;
    this->control_name.assign(
        static_cast<const char*>(buf) + offset + pos, __control_name_len__ - 1);
    pos += __control_name_len__;

    tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->event_type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->pose._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->menu_entry_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mouse_point._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->mouse_point_valid, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int InteractiveMarkerFeedback::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += this->client_id.size() + 4 + 1;
    enc_size += this->marker_name.size() + 4 + 1;
    enc_size += this->control_name.size() + 4 + 1;
    enc_size += __byte_encoded_array_size(NULL, 1);
    enc_size += this->pose._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->mouse_point._getEncodedSizeNoHash();
    enc_size += __boolean_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t InteractiveMarkerFeedback::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == InteractiveMarkerFeedback::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, InteractiveMarkerFeedback::getHash };

    uint64_t hash = 0xd44e20643fb0d4f7LL +
         std_msgs::Header::_computeHash(&cp) +
         geometry_msgs::Pose::_computeHash(&cp) +
         geometry_msgs::Point::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
