/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __visualization_msgs_InteractiveMarkerUpdate_hpp__
#define __visualization_msgs_InteractiveMarkerUpdate_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>
#include <vector>
#include "visualization_msgs/InteractiveMarker.hpp"
#include "visualization_msgs/InteractiveMarkerPose.hpp"

namespace visualization_msgs
{

class InteractiveMarkerUpdate
{
    public:
        int32_t    markers_length;

        int32_t    poses_length;

        int32_t    erases_length;

        std::string server_id;

        int64_t    seq_num;

        uint8_t    type;

        /**
         * LCM Type: visualization_msgs.InteractiveMarker[markers_length]
         */
        std::vector< visualization_msgs::InteractiveMarker > markers;

        /**
         * LCM Type: visualization_msgs.InteractiveMarkerPose[poses_length]
         */
        std::vector< visualization_msgs::InteractiveMarkerPose > poses;

        /**
         * LCM Type: string[erases_length]
         */
        std::vector< std::string > erases;

    public:
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   KEEP_ALIVE = 0;
        // If you're using C++11 and are getting compiler errors saying
        // things like ‘constexpr’ needed for in-class initialization of
        // static data member then re-run lcm-gen with '--cpp-std=c++11'
        // to generate code that is compliant with C++11
        static const int8_t   UPDATE = 1;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "InteractiveMarkerUpdate"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int InteractiveMarkerUpdate::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int InteractiveMarkerUpdate::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int InteractiveMarkerUpdate::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t InteractiveMarkerUpdate::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* InteractiveMarkerUpdate::getTypeName()
{
    return "InteractiveMarkerUpdate";
}

int InteractiveMarkerUpdate::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->markers_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->poses_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->erases_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* server_id_cstr = const_cast<char*>(this->server_id.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &server_id_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->seq_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->markers_length; a0++) {
        tlen = this->markers[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->poses_length; a0++) {
        tlen = this->poses[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->erases_length; a0++) {
        char* __cstr = const_cast<char*>(this->erases[a0].c_str());
        tlen = __string_encode_array(
            buf, offset + pos, maxlen - pos, &__cstr, 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int InteractiveMarkerUpdate::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->markers_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->poses_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->erases_length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __server_id_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__server_id_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__server_id_len__ > maxlen - pos) return -1;
    this->server_id.assign(
        static_cast<const char*>(buf) + offset + pos, __server_id_len__ - 1);
    pos += __server_id_len__;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->seq_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->markers.resize(this->markers_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->markers_length; a0++) {
        tlen = this->markers[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->poses.resize(this->poses_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->poses_length; a0++) {
        tlen = this->poses[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->erases.resize(this->erases_length);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->erases_length; a0++) {
        int32_t __elem_len;
        tlen = __int32_t_decode_array(
            buf, offset + pos, maxlen - pos, &__elem_len, 1);
        if(tlen < 0) return tlen; else pos += tlen;
        if(__elem_len > maxlen - pos) return -1;
        this->erases[a0].assign(static_cast<const char*>(buf) + offset + pos, __elem_len -  1);
        pos += __elem_len;
    }

    return pos;
}

int InteractiveMarkerUpdate::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->server_id.size() + 4 + 1;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->markers_length; a0++) {
        enc_size += this->markers[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->poses_length; a0++) {
        enc_size += this->poses[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->erases_length; a0++) {
        enc_size += this->erases[a0].size() + 4 + 1;
    }
    return enc_size;
}

uint64_t InteractiveMarkerUpdate::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == InteractiveMarkerUpdate::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, InteractiveMarkerUpdate::getHash };

    uint64_t hash = 0xf6eebb4c4a608b4cLL +
         visualization_msgs::InteractiveMarker::_computeHash(&cp) +
         visualization_msgs::InteractiveMarkerPose::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
